cites {
    shape: sql_table

    id_city: serial not null { constraint primary key }
    name_ru: varchar(128) not null
    name_en: varchar(128) not null
}

name_of_analyzes {
    shape: sql_table

    id_analyzes: serial not null { constraint primary key }
    name: varchar(256) not null
    key_word: varchar(64) not null
}