version: '3.9'
services:
  redis:
    image: 'redis:alpine'
#    build: ./redis
    ports:
      - '6379:6379'
  service:
    restart: on-failure
    build: ./server
    ports:
      - '8080:8080'
    links:
      - redis
#  nginx:
#    build: ./nginx
#    ports:
#      - '80:80'
#    depends_on:
#      - server_compare_labs