version: '3.9'
services:
  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
  service:
    restart: on-failure
    build: ./server_compare_labs
    ports:
      - '81:5000'
  nginx:
    build: ./nginx
    ports:
      - '80:80'
    depends_on:
      - server_compare_labs