version: '3.9'
services:
  redis:
    container_name: cmp-lab-redis
    restart: on-failure
    build: redis
    ports:
      - '6379:6379'
  srv:
    restart: on-failure
    build: server
    depends_on:
      - redis
  nginx:
    container_name: nginx-reverse-proxy
    restart: on-failure
    build: nginx
    ports:
      - "8888:80"
      - "443:443"
    depends_on:
      - srv
