version: '3.9'
services:
  redis:
    container_name: cmp-lab-redis
    build: ./redis
    ports:
      - '6379:6379'
  service-1:
    restart: on-failure
    build: ./server
    environment:
      PORT: 8881
    ports:
      - '8881:8881'
    links:
      - redis
  service-2:
    restart: on-failure
    build: ./server
    environment:
      PORT: 8882
    ports:
      - '8882:8882'
    links:
      - redis
  nginx:
    container_name: nginx-reverse-proxy
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    links:
      - service-1
      - service-2