name: deploy cmp-lab-srv to docker hub

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  DOCKER_REPO_NAME: venikshow/cmp-lab-srv # Название нового образа, которое вы хотите записать в Docker Hub
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }} # Логин от Docker Hub
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }} # Пароль от Docker Hub

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./server/Dockerfile
          push: true
          tags: ${{ env.DOCKER_REPO_NAME }}:latest
          platforms: linux/amd64,linux/arm64