name: Golang

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  GIN_MODE: release
  # server
  HOST: http://localhost
  PORT: 8080

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    # install dependencies
    - name: Install dependencies
      working-directory: ./server
      run: |
        go version
        go get -u -v ./...

    # test build
    - name: Build
      working-directory: ./server
      run: |
        go build -v ./...

  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Install dependencies
        working-directory: ./server
        run: |
          go version
          go get -u -v ./...
      

      # run unit tests
      - name: Tests
        working-directory: ./server/tests
        run: |
          go test -v ./...
